package UI;

import DAL.AddPurchase;
import DAL.DeleteShoes;
import DAL.GetCustomers;
import DAL.GetShoes;
import Models.Customer;
import Models.Purchase;
import Models.Shoe;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kevin
 */
public class MirandasShoesUI extends javax.swing.JFrame {

    /**
     * Creates new form MirandasShoesUI
     */
    public MirandasShoesUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCustomers = new javax.swing.JList<>();
        btnRetrieveShoes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShoes = new javax.swing.JTable();
        btnPurchase = new javax.swing.JButton();
        btnAddShoe = new javax.swing.JButton();
        btnDeleteShoe = new javax.swing.JButton();
        btnUpdateShoe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnAddCustomer = new javax.swing.JButton();
        btnRetrieveCustomers = new javax.swing.JButton();
        btnClearSelections = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lstCustomers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCustomers);

        btnRetrieveShoes.setBackground(new java.awt.Color(172, 222, 247));
        btnRetrieveShoes.setText("Retrieve Shoes");
        btnRetrieveShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveShoesActionPerformed(evt);
            }
        });

        tblShoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Brand", "Type", "Color", "Size", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblShoes);

        btnPurchase.setText("New Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnAddShoe.setBackground(new java.awt.Color(126, 206, 126));
        btnAddShoe.setText("Add Shoe");
        btnAddShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddShoeActionPerformed(evt);
            }
        });

        btnDeleteShoe.setBackground(new java.awt.Color(255, 102, 102));
        btnDeleteShoe.setText("Delete Shoe");
        btnDeleteShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteShoeActionPerformed(evt);
            }
        });

        btnUpdateShoe.setBackground(new java.awt.Color(233, 166, 86));
        btnUpdateShoe.setText("Update Shoe");
        btnUpdateShoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateShoeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Inventory");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Customers");

        btnAddCustomer.setText("Add Customer");
        btnAddCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCustomerActionPerformed(evt);
            }
        });

        btnRetrieveCustomers.setBackground(new java.awt.Color(172, 222, 247));
        btnRetrieveCustomers.setText("Retrieve Customers");
        btnRetrieveCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrieveCustomersActionPerformed(evt);
            }
        });

        btnClearSelections.setText("Clear Selections");
        btnClearSelections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSelectionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRetrieveShoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddShoe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeleteShoe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnUpdateShoe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnClearSelections, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(btnPurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(btnRetrieveCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetrieveShoes)
                            .addComponent(btnRetrieveCustomers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddShoe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUpdateShoe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteShoe)
                                .addGap(18, 18, 18)
                                .addComponent(btnClearSelections))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPurchase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddCustomer)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retrieveShoes() {
        GetShoes ms = new GetShoes();
        DefaultTableModel tblShoesModel = (DefaultTableModel) tblShoes.getModel();
        int rows = tblShoesModel.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            tblShoesModel.removeRow(i);
        }
        for (Shoe shoe : ms.shoeList) {
            tblShoesModel.addRow(new Object[]{shoe.getId(), shoe.getName(), shoe.getBrand(), shoe.getType(), shoe.getColor(), shoe.getSize(), shoe.getPrice()});
        }
        //lstShoes.setModel(model);
        tblShoes.setModel(tblShoesModel);
    }
    
    private void retrieveCustomers() {
        GetCustomers gc = new GetCustomers();
        DefaultListModel lm = new DefaultListModel();
        ArrayList<Customer> customers = gc.customerList;
        for (Customer c : customers) {
            lm.addElement(c.getFirstName() + " " + c.getLastName());
        }
        lstCustomers.setModel(lm);
    }

    private void btnRetrieveShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveShoesActionPerformed
        // TODO add your handling code here:
        retrieveShoes();
    }//GEN-LAST:event_btnRetrieveShoesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lblLogo.setIcon(new ImageIcon("mirandasShoes.png"));
        retrieveCustomers();
    }//GEN-LAST:event_formWindowOpened

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
        if (tblShoes.getSelectedRow() > -1 && lstCustomers.getSelectedIndex() > -1) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            double subtotal = 0;
            int selectedRows[] = tblShoes.getSelectedRows();
            for (int i : selectedRows) {
                subtotal += Double.valueOf(tblShoes.getValueAt(i, 6).toString());
            }
            int dialogResult = JOptionPane.showConfirmDialog(null, "Subtotal: $" + subtotal + "\nTax: 15%" + "\nTotal: $" + String.format("%.2f",(subtotal * 1.15)) + "\nYour total is $" + String.format("%.2f",(subtotal * 1.15)) + ". Confirm purchase?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                ArrayList<Purchase> purchases = new ArrayList<>();
                for (int i : selectedRows) {
                    Purchase p = new Purchase();
                    p.setShoeID(tblShoes.getValueAt(i, 0).toString());
                    p.setCustomer(lstCustomers.getSelectedValue());
                    p.setTotal(Double.valueOf(tblShoes.getValueAt(i, 6).toString()));
                    purchases.add(p);
                }
                AddPurchase addPurchase = new AddPurchase();
                addPurchase.AddPurchase(purchases);
                retrieveShoes();
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select one or more shoes from the inventory and a customer");
        }
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnAddShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddShoeActionPerformed
        // TODO add your handling code here:
        AddShoeUI addShoe = new AddShoeUI();
        addShoe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addShoe.setVisible(true);
    }//GEN-LAST:event_btnAddShoeActionPerformed

    private void btnUpdateShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateShoeActionPerformed
        // TODO add your handling code here:
        if (tblShoes.getSelectedRow() > -1) {
            Shoe s = new Shoe();
            s.setId(tblShoes.getValueAt(tblShoes.getSelectedRow(), 0).toString());
            s.setName(tblShoes.getValueAt(tblShoes.getSelectedRow(), 1).toString());
            s.setBrand(tblShoes.getValueAt(tblShoes.getSelectedRow(), 2).toString());
            s.setType(tblShoes.getValueAt(tblShoes.getSelectedRow(), 3).toString());
            s.setColor(tblShoes.getValueAt(tblShoes.getSelectedRow(), 4).toString());
            s.setSize((double) tblShoes.getValueAt(tblShoes.getSelectedRow(), 5));
            s.setPrice((double) tblShoes.getValueAt(tblShoes.getSelectedRow(), 6));
            UpdateShoeUI updateShoe = new UpdateShoeUI(s);
            updateShoe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            updateShoe.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a shoe to update");
        }
    }//GEN-LAST:event_btnUpdateShoeActionPerformed

    private void btnDeleteShoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteShoeActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Delete the selected shoes", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            int selectedRows[] = tblShoes.getSelectedRows();
            ArrayList<Shoe> shoesToDelete = new ArrayList<Shoe>();
            for (int i : selectedRows) {
                Shoe s = new Shoe();
                s.setId(tblShoes.getValueAt(i, 0).toString());
                shoesToDelete.add(s);
            }
            DeleteShoes deleteShoe = new DeleteShoes();
            deleteShoe.DeleteShoe(shoesToDelete);
            retrieveShoes();
        }
    }//GEN-LAST:event_btnDeleteShoeActionPerformed

    private void btnAddCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCustomerActionPerformed
        // TODO add your handling code here:
        AddCustomerUI addCustomerUI = new AddCustomerUI();
        addCustomerUI.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addCustomerUI.setVisible(true);
    }//GEN-LAST:event_btnAddCustomerActionPerformed

    private void btnRetrieveCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrieveCustomersActionPerformed
        // TODO add your handling code here:
        retrieveCustomers();
    }//GEN-LAST:event_btnRetrieveCustomersActionPerformed

    private void btnClearSelectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSelectionsActionPerformed
        // TODO add your handling code here:
        tblShoes.clearSelection();
        lstCustomers.clearSelection();
    }//GEN-LAST:event_btnClearSelectionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MirandasShoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MirandasShoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MirandasShoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MirandasShoesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MirandasShoesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCustomer;
    private javax.swing.JButton btnAddShoe;
    private javax.swing.JButton btnClearSelections;
    private javax.swing.JButton btnDeleteShoe;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnRetrieveCustomers;
    private javax.swing.JButton btnRetrieveShoes;
    private javax.swing.JButton btnUpdateShoe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JList<String> lstCustomers;
    private javax.swing.JTable tblShoes;
    // End of variables declaration//GEN-END:variables
}
